### ISSUE TITLE
Request for serializer named Ceras

### ISSUE THREAD

**Issue by TechInterMezzo** [Alois-xx/SerializerTests#12]
This is the repository:
https://github.com/rikimaru0345/Ceras

The developer did his own benchmarks but I would really love to see the results in your test suit.

**Comment by Alois-xx** [comment]
I have added Ceras to the test suite but it does not support MemoryStreams so this might be a little unfair. 

D:\Source\git\SerializerTests\bin\Release\net472>SerializerTests.exe -test combined -Runs 3 -N 1000000 -serializer apex,ceras
Serializer      Objects "Time to serialize in s"        "Time to deserialize in s"      "Size in bytes" FileVersion     Framework       ProjectHome     DataFormat      FormatDetails   Supports Versioning
ApexSerializer  1000000 0.0177  0.136   30826428        1.3.0.0 .NET Framework 4.8.4010.0       https://github.com/dbolin/Apex.Serialization    Binary          No
Ceras   1000000 0.2920  0.389   15880647        4.1.7.0 .NET Framework 4.8.4010.0       https://github.com/rikimaru0345/Ceras   Binary          Yes

Ceras is ca. 3 times slower than Apex. But I need to convert the MemoryStream to an array before I can pass it to Ceras. That comes with a significant cost.

**Comment by Alois-xx** [comment]
Its now in the test suite with the fastest overloads I could see. But Arraypooling does not improve things much.
