### ISSUE TITLE
New benchmark for January 2020

### ISSUE THREAD

**Issue by silkfire** [Alois-xx/SerializerTests#16]
Would you be able to write another blog post summarizing the benchmarks that have been added since sep 2019? Would be really useful.

**Comment by Alois-xx** [comment]
Depending on feedback I will write another round in 2020 but not in the first half of 2020. For an overview it should be enough. The actual performance depends not on the things I write but on your specific needs and data format. My tests can only give hints which serializers are worth considering for your specific use case. But you may find critical features missing for your needs when you want to use the really fast ones. Real world issues would be great as comments on my blog. That would help to get some overview about common pitfalls of this or that serializer.

**Comment by AloisKraus** [comment]
It did take longer to reach some interesting critical mass again. https://aloiskraus.wordpress.com/2022/11/23/net-serialization-roundup-2022/
