### ISSUE TITLE
System.Text.Json source generators

### ISSUE THREAD

**Issue by lbargaoanu** [Alois-xx/SerializerTests#23]
Maybe the test should use those.
I've tried it on .NET 7 and didn't seem to get better results. Better startup, yes, but other than a regression for 200000 objects, nothing notable.
Perhaps I've missed smth.
I do see a significant improvement in the test [here](https://github.com/Cysharp/MemoryPack/blob/main/sandbox/Benchmark/Benchmarks/SerializeTest.cs#L107). Maybe the test object is too small, it only has a few properties.

**Comment by Alois-xx** [comment]
That would only make a difference for AOT binaries which have no JIT compiler anymore. Just pregenerating the code will just save the code generation, but not the JIT compilation time, except if the binary is crossgenned. 
There are quite a few cases which are not covered, but this should only affect startup time, but not runtime.

**Comment by lbargaoanu** [comment]
That's not what [they say](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/#how-source-generation-provides-benefits). And my test in the MemoryPack repo confirms that. Source generators do seem to be faster. And the `Person` type they have it's small too, contradicting my guess. Maybe it's smth that shows only in a microbenchmark :)

**Comment by Alois-xx** [comment]
I also see a significant gain for serialize but the code is strange. Precompiled code is only existing for serialization and you have to fallback to Metadata for deserialization, but the overloads all excpect a string or ReadOnlySpan<char>. 
The documentation is not really detailing why you would ever want to use JsonSourceGenerationMode.MetaData when you can have JsonSourceGenerationMode.Serialization. Based on my experiments it looks like that the generated code currently only covers serialization? That looks like this feature is still half finished. Perhaps .NET 8.0 will cover everything.

**Comment by Alois-xx** [comment]
I have added a testcase for it. See latest commit. [6241813](https://github.com/Alois-xx/SerializerTests/commit/62418132780ce8b75cb6205083e13b7e7f71e6af)

**Comment by lbargaoanu** [comment]
I repeated the tests a few times. The serialize gains seem legit, but for deserialize, I don't know anymore. Just noise I guess.
