### ISSUE TITLE
Can't build solution

### ISSUE THREAD

**Issue by aienabled** [Alois-xx/SerializerTests#3]
Hello!
Congrats for making a great serializer tests suite!
I'm very interested in integrating my binary serializer and comparing it with others.

I just pulled the repository, opened it with VS2017, restored the NuGet packages, but can't build it because of this conflict:
```The type 'JSONParameters' exists in both 'fastJSON, Version=2.1.0.0, Culture=neutral, PublicKeyToken=6b75a806b86095cd' and 'fastJSON, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'```

I temporary commented out all the code related to fastJSON, but would prefer to restore it for full comparison and eventual pull-request adding my binary serializer.

Regards!

**Comment by Alois-xx** [comment]
Yes I had the same problem. I have "fixed" this by modifying the referenced version and copyed the .NETStandard dll from the repository which seems to link against the right library. 

`copy "%USERPROFILE%\.nuget\packages\fastjson\2.1.28\lib\netstandard2.0\fastjson.dll" %USERPROFILE%\.nuget\packages\fastjson\2.1.28\lib\net40`

That should do the trick for now.

**Comment by Alois-xx** [comment]
I have opened an issue at FastJson for now.
